# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and Push image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sboulema/rabbitmq-alert'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/RabbitMQ-Alert/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest